{"uuid":"343a8af1-f3b4-42f7-9d40-f6bddfd3251c","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Test argument \"title\" should be a string. Received type \"undefined\"\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Test argument \"title\" should be a string. Received type \"undefined\"\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at createInvalidArgumentTypeError (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:109524:13)\n    at new Test (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:116313:11)\n    at context.it.context.specify (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:109724:18)\n    at createRunnable (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:165596:31)\n    at <unknown> (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:165657:14)\n    at Object.create (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:109903:19)\n    at context.describe.context.context (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:109679:27)\n    at createRunnable (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:165596:31)\n    at <unknown> (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:165657:14)\n    at <unknown> (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:168270:23)\nFrom previous event:\n    at evalScripts (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:168265:58)\n    at <unknown> (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:168274:152)\nFrom previous event:\n    at runScriptsFromUrls (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:168274:136)\n    at Object.runScripts (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:168288:12)\n    at $Cypress.onSpecWindow (https://conduit.productionready.io/__cypress/runner/cypress_runner.js:156922:75)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress\\e2e\\todos_e2e\\trainOnTodos.spec.cy.ts"}],"links":[],"start":1696589818764,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1696589818769}